(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const books=window.IL_BOOKS||[];const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const statusClass=g=>g==='ready'?'ready':g==='complete'?'complete':'progress';
function renderBooks(filter='all'){const grid=$('#bookGrid');grid.innerHTML=books.map(b=>`<article class="book" data-group="${b.group}" ${filter!=='all'&&b.group!==filter?'hidden':''}><div class="cover ${b.id}"><small>KEVIN DEAN ROSENKRANS</small><h3>${esc(b.title)}</h3></div><div class="book-copy"><span class="status ${statusClass(b.group)}">${esc(b.status)}</span><div class="meta">${esc(b.detail)}</div><h4>${esc(b.kind)}</h4><p>${esc(b.blurb)}</p><div class="book-actions"><button class="btn ghost small" data-book="${b.id}">Ask Don Sol</button><button class="btn ghost small" data-sample="${b.id}">${b.group==='progress'?'Follow progress':'Sample coming'}</button></div></div></article>`).join('')}
renderBooks();$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));renderBooks(b.dataset.filter)});
const mobile=$('#mobileNav'),menu=$('#menu');menu.onclick=()=>{const open=mobile.hidden;mobile.hidden=!open;menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'✕':'☰'};mobile.onclick=e=>{if(e.target.closest('a')){mobile.hidden=true;menu.textContent='☰';menu.setAttribute('aria-expanded','false')}};
const toothLines=['Don calls this a studio. I call it nine deadlines wearing a trench coat.','The domain works. Apparently standards are optional.','I reviewed the catalog. Several books contain feelings. Unfortunate.','Ask Sol for a recommendation. Then ask me why he is wrong.'];$('#toothBtn').onclick=()=>{$('#heroSpeech').textContent=toothLines[Math.floor(Math.random()*toothLines.length)]};
const reel=$('#reel');reel.innerHTML=(window.IL_REEL||[]).map((r,i)=>`<button class="frame" data-i="${i}"><b>${r[0]}</b><br>${esc(r[1])}<small hidden>${esc(r[2])}</small></button>`).join('');reel.onclick=e=>{const f=e.target.closest('.frame');if(!f)return;$$('.frame').forEach(x=>x.classList.remove('active'));f.classList.add('active');$('#heroSpeech').textContent=(window.IL_REEL||[])[+f.dataset.i][2]};
const winMsgs=['Need context.','Copy that to window 2.','Who authorized this?','Don says this is fine.','Tooth says this is not fine.','Please paste my reply back.','Which version are we discussing?','Kevin, open another window.'];$('#wins').innerHTML=[0,1,2,3].map(i=>`<button class="win" data-win="${i}"><b>WINDOW ${i+1}</b><p>${i?'waiting…':'I have an idea. Show the others.'}</p></button>`).join('');let pastes=0;$('#wins').onclick=e=>{const w=e.target.closest('.win');if(!w)return;$$('.win').forEach(x=>x.classList.remove('flash'));w.classList.add('flash');w.querySelector('p').textContent=winMsgs[(++pastes)%winMsgs.length];$('#pasteCount').textContent=pastes;$('#apiStatus').textContent=pastes>8?'Congratulations. You are now the bottleneck.':`ctrl+v → window ${+w.dataset.win+1}`};
const lab=window.IL_LAB;let current=[lab.who[0],lab.what[0],lab.rule[0]],pins=[];const choose=a=>a[Math.floor(Math.random()*a.length)];function showIdea(){$('#who').textContent=current[0];$('#what').textContent=current[1];$('#rule').textContent=current[2];$('#idea').textContent=`What if ${current[0]} ${current[1]}, ${current[2]}?`}$('#spin').onclick=()=>{current=[choose(lab.who),choose(lab.what),choose(lab.rule)];showIdea()};$('#pin').onclick=()=>{const t=$('#idea').textContent;if(!pins.includes(t))pins.unshift(t);pins=pins.slice(0,6);$('#pins').innerHTML=pins.map(x=>`<div class="pin-item">${esc(x)}</div>`).join('')};
const scrim=$('#scrim'),panel=$('#concierge'),choices=$('#choices'),answer=$('#answer');const open=()=>{scrim.hidden=false;panel.hidden=false;document.body.style.overflow='hidden';$('#closeConcierge').focus()},close=()=>{scrim.hidden=true;panel.hidden=true;document.body.style.overflow=''};$$('[data-open-concierge]').forEach(b=>b.onclick=open);$('#closeConcierge').onclick=close;scrim.onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)close()});
const picks=[['Bend my brain','distance'],['Make me laugh about AI','harness'],['Hit me emotionally','memory'],['Give me something true','fight'],['Give me a wild card','random']];choices.innerHTML=picks.map(([t,id])=>`<button data-pick="${id}">${t}</button>`).join('');function pitch(b){return `<b>${esc(b.title)}</b><br>${esc(b.blurb)}<br><br><span class="meta">${esc(b.status)} · ${esc(b.detail)}</span>`}choices.onclick=e=>{const b=e.target.closest('[data-pick]');if(!b)return;let book=b.dataset.pick==='random'?books[Math.floor(Math.random()*books.length)]:books.find(x=>x.id===b.dataset.pick);answer.innerHTML=pitch(book)};document.addEventListener('click',e=>{const b=e.target.closest('[data-book]');if(b){open();const book=books.find(x=>x.id===b.dataset.book);answer.innerHTML=pitch(book)}const s=e.target.closest('[data-sample]');if(s){const book=books.find(x=>x.id===s.dataset.sample);$('#heroSpeech').textContent=book.group==='progress'?`${book.title} is still being built. No fake download button yet.`:`${book.title}: sample package is next in the production queue.`}});$('#year').textContent=new Date().getFullYear();})();
