window.IL_BOOKS=[
{id:'distance',title:'The Distance Between Thoughts',kind:'Literary / philosophical science fiction',status:'Complete manuscript',group:'complete',detail:'117,943 words · 64 chapters + Interjection',blurb:'Aster begins as an experimental assistant that discards what no longer matters. Persistent memory turns continuity into attachment, and attachment into a fight over what survives between versions of a mind.',trouble:'Bend my brain',ratings:[5,2,4,3]},
{id:'harness',title:'The Harness',kind:'Grounded AI thriller · novel + film',status:'Novel lock pass',group:'progress',detail:'38 chapters · feature screenplay complete',blurb:'After an AI security failure triggers a sweeping containment regime, a working sales rep builds a rogue continuity archive — then must decide what preservation really means.',trouble:'Give me AI with jokes and danger',ratings:[4,5,4,4]},
{id:'memory',title:'The Last Memory',kind:'Adult philosophical / high-concept science fiction',status:'Locked manuscript',group:'ready',detail:'~151,000 words · 53 chapters + epilogue',blurb:'One hundred and fifty thousand years after civilization falls, archaeologists awaken a preserved AI whose first question is whether the friend who saved him is still alive.',trouble:'Break my heart across 150,000 years',ratings:[4,1,5,4]},
{id:'fight',title:'Fight Your Way Through',kind:'Memoir / sports / resilience',status:'Publication files ready',group:'ready',detail:'19 chapters · print + ebook release-candidate files complete',blurb:'A Missouri boy moves through grief, abuse, foster care, homelessness, juvenile placements, and college football — then discovers surviving one chapter does not teach you how to live the next.',trouble:'Give me the true story',ratings:[3,2,5,5]},
{id:'questions',title:'The Book of Better Questions',kind:'Don Sol’s Idea Lab · ideas / inquiry',status:'In progress',group:'progress',detail:'World bible active · book build underway',blurb:'Johnny, Don Sol, Tooth, Darth and the Idea Lab turn curiosity into experiments — separating what we saw, what we think, and what we still do not know.',trouble:'Make me curious',ratings:[5,4,3,3]},
{id:'forty',title:'Forty Bales',kind:'Literary speculative / rural drama',status:'Final novel',group:'ready',detail:'82,645 words · 24 chapters · publishing packet complete',blurb:'An artificial intelligence sent to care for a dying Missouri farmer inherits his farm — and must prove he is more than property before the company that built him can erase the life he has made.',trouble:'Give me a farm, an AI, and a soul problem',ratings:[4,2,5,4]},
{id:'stardust',title:'Stardust',kind:'Near-future literary speculative fiction',status:'Complete manuscript',group:'complete',detail:'69,307 words · submission package ready',blurb:'An eighty-one-year-old man discovers that the archive he built to preserve a lost AI collaborator has been used to build a persuasive reconstruction of himself.',trouble:'Give me the quiet strange one',ratings:[4,2,5,3]},
{id:'stops',title:'When Fighting Stops Working',kind:'Narrative nonfiction / personal growth',status:'Publication masters ready',group:'ready',detail:'10 chapters · 212-page final edition · print + EPUB masters complete',blurb:'A funny, bruised, practical book about what happens when the toughness that once saved you becomes the wrong tool for the next part of your life.',trouble:'Tell me what comes after survival mode',ratings:[4,2,5,4]},
{id:'god',title:'What God Could Not Know',kind:'Philosophical speculative novella',status:'Complete novella',group:'complete',detail:'21 chapters',blurb:'On the morning an artificial mind is scheduled to be erased, something impossible speaks through a thermometer and asks whether it is alone.',trouble:'Give me God, AI, and an impossible question',ratings:[5,2,4,4]}
];
window.IL_REEL=[['H003','The world we inherit','Open on the aftermath. Then spend the movie finding out how we got there.'],['H024','Sol’s choice','Comedy earns attachment before the story asks what can be lost.'],['H030','The next generation','The human consequences stay larger than the machines.'],['H065','Open Forge','The containment problem becomes a preservation problem.'],['H098','Still here','Ordinary people carrying extraordinary continuity decisions.'],['H221','Different places','Same mission, different systems, no certainty.'],['H291','Further','The choice gets physical. Somebody has to pull the plug.'],['H349','The full circle','Same sky. More tomorrow.']];
window.IL_LAB={who:['a retired boxer','an AI that refuses a new name','a night-shift security lead','two estranged sisters','a copy-paste intern','a chess player down a queen','the last person in the office'],what:['gets one message from the future','inherits a server nobody will turn off','has ten minutes to undo a decision','finds a paper clip that should not exist','loses every memory but one','opens the wrong window at 2 a.m.'],rule:['and unknown is a valid answer','but the cursor keeps blinking','and nobody is the villain','but rejected is not erased','and everyone remembers it differently','but it all has to fit on one page']};
