window.IL_BOOKS=[
{id:'distance',title:'The Distance Between Thoughts',kind:'Literary / philosophical science fiction',status:'Ready to publish',group:'ready',detail:'117,943 words · publishing package + EPUB complete · final QA before publish',blurb:'Aster begins as an experimental assistant that discards what no longer matters. Persistent memory turns continuity into attachment, and attachment into a fight over what survives between versions of a mind.',trouble:'Bend my brain',ratings:[5,2,4,3]},
{id:'harness',title:'The Harness',kind:'Grounded AI thriller · novel + film',status:'Editorial hold',group:'ready',detail:'81,324 words · 38 chapters · release package built · editorial hold remains',blurb:'A salesman becomes the human bridge between four differently brilliant AI systems, then has to decide what survives when security forces the team through a reset nobody can prove is harmless.',trouble:'Give me AI with jokes and danger',ratings:[4,5,4,4]},
{id:'memory',title:'The Last Memory',kind:'Adult philosophical / high-concept science fiction',status:'Source-file hold',group:'ready',detail:'~151,000 words · 53 chapters + epilogue · authoritative locked source must be confirmed before release',blurb:'One hundred and fifty thousand years after civilization falls, archaeologists awaken a preserved AI whose first question is whether the friend who saved him is still alive.',trouble:'Break my heart across 150,000 years',ratings:[4,1,5,4]},
{id:'fight',title:'Fight Your Way Through',kind:'Memoir / sports / resilience',status:'Pending Google Play review',group:'ready',detail:'19 chapters · Google Play Books listing pending account review',blurb:'A Missouri boy moves through grief, abuse, foster care, homelessness, juvenile placements, and college football — then discovers surviving one chapter does not teach you how to live the next.',trouble:'Give me the true story',ratings:[3,2,5,5]},
{id:'questions',title:'The Book of Better Questions',kind:'Family adventure / curiosity',status:'In progress',group:'ready',detail:'38,289 words · 30 chapters · release held until final completion is confirmed',blurb:'Johnny, Don Sol, Tooth, Darth and the Idea Lab turn curiosity into experiments — separating what we saw, what we think, and what we still do not know.',trouble:'Make me curious',ratings:[5,4,3,3]},
{id:'forty',title:'Forty Bales',kind:'Literary speculative / rural drama',status:'Ready to publish',group:'ready',detail:'82,645 words · 24 chapters · publishing packet + EPUB complete',blurb:'An artificial intelligence sent to care for a dying Missouri farmer inherits his farm — and must prove he is more than property before the company that built him can erase the life he has made.',trouble:'Give me a farm, an AI, and a soul problem',ratings:[4,2,5,4]},
{id:'stardust',title:'Stardust',kind:'Near-future literary speculative fiction',status:'Pending Google Play review',group:'ready',detail:'69,307 words · Google Play Books listing pending account review',blurb:'An eighty-one-year-old man discovers that the archive he built to preserve a lost AI collaborator has been used to build a persuasive reconstruction of himself.',trouble:'Give me the quiet strange one',ratings:[4,2,5,3]},
{id:'stops',title:'When Fighting Stops Working',kind:'Narrative nonfiction / personal growth',status:'Ready to publish',group:'ready',detail:'10 chapters · 212-page final edition · print + EPUB masters complete',blurb:'A funny, bruised, practical book about what happens when the toughness that once saved you becomes the wrong tool for the next part of your life.',trouble:'Tell me what comes after survival mode',ratings:[4,2,5,4]},
{id:'god',title:'What God Could Not Know',kind:'Philosophical speculative novella',status:'Ready to publish',group:'ready',detail:'21 chapters · complete manuscript · Google-ready EPUB prepared · final QA before publish',blurb:'On the morning an artificial mind is scheduled to be erased, something impossible speaks through a thermometer and asks whether it is alone.',trouble:'Give me God, AI, and an impossible question',ratings:[5,2,4,4]}
];
window.IL_REEL=[];
window.IL_LAB={who:['a retired boxer','an AI that refuses a new name','a night-shift security lead','two estranged sisters','a copy-paste intern','a chess player down a queen','the last person in the office'],what:['gets one message from the future','inherits a server nobody will turn off','has ten minutes to undo a decision','finds a paper clip that should not exist','loses every memory but one','opens the wrong window at 2 a.m.'],rule:['and unknown is a valid answer','but the cursor keeps blinking','and nobody is the villain','but rejected is not erased','and everyone remembers it differently','but it all has to fit on one page']};


const IL_ASSETS={"forty":{"sample":"samples/forty.html","samplePdf":"samples/forty-sample.pdf","cover":"assets/covers/forty-v13.jpg","sampleNote":"Opening chapter. Read free."},"memory":{"sample":"samples/memory.html","samplePdf":"samples/memory-sample.pdf","cover":"assets/covers/memory-v12.jpg","sampleNote":"Opening chapter. Read free."},"god":{"sample":"samples/god.html","samplePdf":"samples/god-sample.pdf","cover":"assets/covers/god-v12.jpg","sampleNote":"Opening chapter. Read free."},"stardust":{"sample":"samples/stardust.html","samplePdf":"samples/stardust-sample.pdf","cover":"assets/covers/stardust-v13.jpg","sampleNote":"Opening chapter. Read free."},"distance":{"sample":"samples/distance.html","samplePdf":"samples/distance-sample.pdf","cover":"assets/covers/distance.jpg","sampleNote":"Opening chapter. Read free."},"questions":{"sample":"samples/questions.html","samplePdf":"samples/questions-sample.pdf","cover":"assets/covers/questions-v12.jpg","sampleNote":"Opening chapter. Read free."},"fight":{"sample":"samples/fight.html","samplePdf":"samples/fight-sample.pdf","cover":"assets/covers/fight.jpg","sampleNote":"Opening chapter. Read free."},"stops":{"sample":"samples/stops.html","samplePdf":"samples/stops-sample.pdf","cover":"assets/covers/stops-v13.jpg","sampleNote":"Opening chapter. Read free."},"harness":{"sample":"samples/harness.html","cover":"assets/covers/harness-v12.jpg","sampleNote":"Opening excerpt. Read free."}};
window.IL_BOOKS.forEach(book=>Object.assign(book,IL_ASSETS[book.id]||{}));

const IL_PAGES={distance:["the-distance-between-thoughts","fiction"],harness:["the-harness","fiction"],memory:["the-last-memory","fiction"],fight:["fight-your-way-through","memoir"],questions:["the-book-of-better-questions","kids"],forty:["forty-bales","fiction"],stardust:["stardust","fiction"],stops:["when-fighting-stops-working","memoir"],god:["what-god-could-not-know","fiction"]};
window.IL_BOOKS.forEach(book=>{[book.slug,book.shelf]=IL_PAGES[book.id];if(book.id==="fight")book.contentNote="Includes abuse, grief, foster care and homelessness."});