const {chromium}=require('playwright');
const fs=require('fs');
const assert=require('assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome',args:['--no-sandbox']});
 const p=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
 const errs=[];p.on('pageerror',e=>errs.push(String(e)));
 const url='http://127.0.0.1:8793/';
 await p.goto(url,{waitUntil:'load'});
 fs.mkdirSync('qa/screenshots',{recursive:true});
 async function shot(n,full=true){await p.screenshot({path:'qa/screenshots/'+n+'.png',fullPage:full})}
 async function click(id){await p.locator('#'+id).click()}
 assert.equal(await p.locator('#game').getAttribute('data-scene'),'title');
 await shot('01-title',false);
 for (const b of ['startButton','relayButton','commandButton']) await click(b);
 assert.equal(await p.locator('#game').getAttribute('data-scene'),'briefing');
 await shot('02-briefing');
 await click('briefingNext');await shot('03-crew',false);await click('missionButton');
 assert.equal(await p.locator('#game').getAttribute('data-scene'),'investigation');
 assert.equal(await p.locator('.case-evidence-card').count(),4);
 await shot('04-investigation');
 await p.locator('[data-evidence="e_monitor"]').click();
 await shot('05-monitor-report');
 await p.locator('[data-evidence="e_controller"]').click();
 await p.locator('[data-consult="tooth"]').click();
 assert((await p.locator('#caseAdvice').innerText()).includes('main clock'));
 await p.locator('[data-consult="boy"]').click();
 assert.equal(await p.locator('.case-evidence-card').count(),5);
 await p.locator('[data-evidence="e_clocksync"]').click();
 await p.locator('[data-consult="tooth"]').click();
 assert((await p.locator('#caseAdvice').innerText()).includes('six minutes'));
 await shot('06-clock-and-advice');
 await click('goDecision');
 assert.equal(await p.locator('#game').getAttribute('data-scene'),'decision');
 assert(await p.locator('[data-decision="d_hybrid"]').isEnabled());
 await shot('07-decision');
 await p.locator('[data-decision="d_hybrid"]').click();
 await p.locator('#uncertaintyCheck').check();
 await click('submitDecision');
 assert.equal(await p.locator('#game').getAttribute('data-scene'),'outcome');
 await shot('08-outcome');
 await click('showDebrief');
 assert.equal(await p.locator('#game').getAttribute('data-scene'),'debrief');
 await shot('09-debrief');
 await click('replayButton');
 assert.equal(await p.locator('#game').getAttribute('data-scene'),'title');
 await p.close();
 const desktop=await browser.newPage({viewport:{width:1280,height:900}});
 desktop.on('pageerror',e=>errs.push(String(e)));
 await desktop.goto(url);
 for(const btn of ['startButton','relayButton','commandButton','briefingNext','missionButton'])await desktop.locator('#'+btn).click();
 await desktop.screenshot({path:'qa/screenshots/10-investigation-desktop.png',fullPage:true});
 await desktop.close();
 await browser.close();
 assert.equal(errs.length,0,'Browser exceptions: '+JSON.stringify(errs));
 fs.writeFileSync('qa/RESULT.txt','PASS: V3 Chromium mobile + desktop, 9 stages, 4 to 5 evidence, conditional TOOTH, hybrid unlock, original outcome, debrief, replay. Browser page errors: 0.\nAudio output on physical Motorola not tested.\n');
 console.log('PASS: hosted Chrome interaction and screenshot run');
})().catch(e=>{console.error('FAIL',e.stack||e);process.exit(1)});
