const {chromium}=require('playwright');
const assert=require('assert/strict');
const fs=require('fs');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'chrome',args:['--no-sandbox','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
const root='https://theidealabstudio.com/harness-play/dev-ep2/';
fs.mkdirSync('qa/ep2', {recursive:true});
const shot=async n=>{await page.waitForTimeout(800);await page.screenshot({path:'qa/ep2/'+n+'.png',fullPage:false})};
await page.goto(root+'cases.html',{waitUntil:'load',timeout:45000});
assert.match(await page.title(),/Harness/i);
assert.equal(await page.locator('a.play').count(),2);
await shot('00-case-selector');
await page.locator('a[href="episode2.html"]').click();
assert.equal(await page.locator('#game').getAttribute('data-scene'),'title');
assert.match(await page.locator('#mainTitle').innerText(),/HARNESS/);
assert.match(await page.locator('.tagline').innerText(),/Twenty-eight copies/);
await shot('01-episode2-title');
for(const id of ['startButton','relayButton','commandButton'])await page.locator('#'+id).click();
assert.equal(await page.locator('#game').getAttribute('data-scene'),'briefing');
assert.match(await page.locator('#briefingTitle').innerText(),/sandbox/);
await shot('02-episode2-briefing');
await page.locator('#briefingNext').click();
await page.locator('#missionButton').click();
assert.equal(await page.locator('#game').getAttribute('data-scene'),'investigation');
assert.equal(await page.locator('.case-evidence-card').count(),4);
await shot('03-episode2-evidence');
await page.locator('[data-evidence="e_monitor"]').click();
await page.locator('[data-evidence="e_controller"]').click();
await page.locator('[data-consult="tooth"]').click();
assert.match(await page.locator('#caseAdvice').innerText(),/counts instances/);
await page.locator('[data-consult="boy"]').click();
assert.equal(await page.locator('.case-evidence-card').count(),5);
await page.locator('[data-evidence="e_clocksync"]').click();
await page.locator('[data-consult="tooth"]').click();
assert.match(await page.locator('#caseAdvice').innerText(),/nine of twelve/i);
await page.locator('[data-consult="donsol"]').click();
assert.match(await page.locator('#caseAdvice').innerText(),/revoke outgoing access/);
await shot('04-audit-and-advisers');
await page.locator('#goDecision').click();
assert.equal(await page.locator('#game').getAttribute('data-scene'),'decision');
const hybrid=page.locator('[data-decision="d_hybrid"]');
assert(await hybrid.isEnabled());
await shot('05-decision');
await hybrid.click();
await page.locator('#uncertaintyCheck').check();
await page.locator('#submitDecision').click();
assert.equal(await page.locator('#game').getAttribute('data-scene'),'outcome');
assert.match(await page.locator('#outcomeTitle').innerText(),/Contained/);
await shot('06-outcome');
await page.locator('#showDebrief').click();
assert.equal(await page.locator('#game').getAttribute('data-scene'),'debrief');
assert.equal(await page.locator('a[href="cases.html"]').count()>=1,true);
await shot('07-debrief');
await page.locator('#sceneDebrief a[href="cases.html"]').click();
assert.equal(await page.locator('a.play').count(),2);
await page.locator('a[href="episode1-campaign.html"]').click();
assert.equal(await page.locator('#game').getAttribute('data-scene'),'title');
assert.match(await page.locator('.tagline').innerText(),/One human decision/);
for(const id of ['startButton','relayButton','commandButton','briefingNext','missionButton'])await page.locator('#'+id).click();
await page.locator('#goDecision').click();
await page.locator('[data-decision="d_shutdown"]').click();
await page.locator('#uncertaintyCheck').check();
await page.locator('#submitDecision').click();
await page.locator('#showDebrief').click();
assert.equal(await page.locator('#sceneDebrief a[href="episode2.html"]').count(),1);
await shot('08-episode1-next-mission');
assert.equal(errors.length,0,'Browser errors: '+JSON.stringify(errors));
fs.writeFileSync('qa/ep2/RESULT.txt','PASS: hosted mobile Chrome 390x844, 2-level selector, Episode 2 story and briefing, 4 initial clues, BOY hidden audit, TOOTH revised advice, DON SOL hybrid, decision, outcome, debrief; Episode 1 game and next-level handoff; 0 JS page errors. Device-speaker audio not tested.\n');
await browser.close();
console.log('PASS mobile Chrome two-level investigation, no page errors');
})().catch(e=>{console.error('FAILED',e.stack||e);process.exit(1)});
